---
- name: Deploy Apache ds.bi using role
  hosts: all
  become: yes
  roles:
    - role: superset
      vars: 
        load_examples: False
        superset_version: 3.1.0

- name: Install redis
  hosts: all
  become: true
  roles:
    - redis