---
# Список пакетов для предварительной установки
pre_install_packages:
  - build-essential
  - libssl-dev
  - libffi-dev
  - python3-dev
  - python3-pip
  - libsasl2-dev
  - libldap2-dev
  - default-libmysqlclient-dev
  - libpq-dev


pip_pre_install:
  - virtualenv

superset_app_icon: "/static/assets/images/app_logo.png"
superset_favicon: "/static/assets/images/favicon.png"