---
- name: Update APT cache
  apt:
    update_cache: yes

- name: Install acl
  apt:
    name: "acl"
    state: present
  become: yes

- name: Install required packages
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ pre_install_packages }}"

- name: Install libraries using pip
  pip:
    name: "{{ item }}"
    state: present
  loop: "{{ pip_pre_install }}"

- name: Create a virtual environment for Superset
  command:
    cmd: "virtualenv {{ superset_venv_path }}"
    creates: "{{ superset_venv_path }}/bin/activate"

- name: Check for '{{ superset_user }}' user
  getent:
    database: passwd
    key: "{{ superset_user }}"
  register: superset_user_check
  ignore_errors: true

- name: Set fact if '{{ superset_user }}' user exists
  set_fact:
    superset_exists: true
  when: "'{{ superset_user }}' in superset_user_check.keys()"

- name: Create '{{ superset_user }}' user if not exists
  block:
    - name: Create 'superset' user
      user:
        name: "{{ superset_user }}"
        state: present

    - name: Add '{{ superset_user }}' user to 'sudo' group
      user:
        name: "{{ superset_user }}"
        groups: sudo
        append: yes

    - name: Allow '{{ superset_user }}' user to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        line: '"{{ superset_user }}" ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
  when: superset_exists is not defined
  become: yes

- name: Create configs of superset
  block:
  - name: Ensure Superset configuration directory exists
    file:
      path: "{{ superset_config_dir }}"
      state: directory
      mode: '0755'
      owner: "{{ superset_user }}"
      group: "{{ superset_group }}"

  - name: Create Superset environment file from template
    template:
      src: superset_env.j2
      dest: "{{ superset_config_dir }}/superset_env.sh"
      mode: '0755'
      owner:  "{{ superset_user }}"
      group:  "{{ superset_group}}"

  - name: Deploy superset_config.py from template
    template:
      src: superset_config.j2
      dest: "{{ superset_config_dir }}/superset_config.py"
      mode: '0644'
      owner:  "{{ superset_user }}"
      group:  "{{ superset_group }}"
  
  become: yes
